version: 1.0.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore
build:
  verbosity: minimal
after_build:
- Zed.NHibernate_build_nuget.bat
artifacts:
- path: Zed.NHibernate.$(APPVEYOR_BUILD_VERSION).nupkg
  name: Zed.NHibernate.$(APPVEYOR_BUILD_VERSION).nupkg
- path: packages
  name: Zed.NHibernate.Packages.$(APPVEYOR_BUILD_VERSION)