environment:
  version_major: 1
  version_minor: 3
  version_patch: 0
version: $(version_major).$(version_minor).$(version_patch).{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(version_major).0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(version_major).$(version_minor).$(version_patch)'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: Zed.NHibernate_build_nuget.bat
artifacts:
- path: Zed.NHibernate.$(version_major).$(version_minor).$(version_patch).nupkg
  name: Zed.NHibernate.$(version_major).$(version_minor).$(version_patch).nupkg
- path: packages
  name: Zed.NHibernate.Packages.$(version_major).$(version_minor).$(version_patch)